<?xml version="1.0" encoding="utf-8"?><Database Name="MindOverMatterDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SAIKIK\SQLEXPRESS;Initial Catalog=MindOverMatterDB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MindOverMatterDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminSurname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AdminEmail" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AdminPassword" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BookConsultation" Member="BookConsultations">
    <Type Name="BookConsultation">
      <Column Name="BookNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BookTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Diary" Member="Diaries">
    <Type Name="Diary">
      <Column Name="DiaryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiaryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaryTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaryDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FlaggedWords" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFlagged" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeidicineTracker" Member="MeidicineTrackers">
    <Type Name="MeidicineTracker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NameOfMedication" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameOfDoctor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notification" Member="Notifications">
    <Type Name="Notification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfNotification" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PrescribeExercise" Member="PrescribeExercises">
    <Type Name="PrescribeExercise">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DatePrescribed" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsLatestCompleted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumCompletion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPrescribed" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Psychologist" Member="Psychologists">
    <Type Name="Psychologist">
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PsychologistName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PsychologistSurname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PsychologistEmail" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PsychologistPassword" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NumStudentsLinked" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="AdminId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SessionNote" Member="SessionNotes">
    <Type Name="SessionNote">
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SessionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SessionDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SessionRating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UnAvailableDateAndTime" Member="UnAvailableDateAndTimes">
    <Type Name="UnAvailableDateAndTime">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Time" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsAvailable" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentPsychologistLink" Member="StudentPsychologistLinks">
    <Type Name="StudentPsychologistLink">
      <Column Name="LinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PsychologistId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLinked" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exercise" Member="Exercises">
    <Type Name="Exercise">
      <Column Name="ExerciseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExerciseName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MediaPath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mood" Member="Moods">
    <Type Name="Mood">
      <Column Name="MoodId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoodDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MoodTime" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MoodEmotion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MoodIntegerImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CallLog" Member="CallLogs">
    <Type Name="CallLog">
      <Column Name="CallId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TelHolder" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TelNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CallDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CallTime" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StudentSurname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StudentEmail" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="StudentPassword" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="StudentGender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StudentDOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StudentQualification" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Campus" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>